### ISSUE TITLE
Database Step One

### ISSUE THREAD

**Issue by lewisjae1** [MejiaJ84/CPW-211-WorkoutBuilder#1]
- [x] Make a diagram to sort out the general structure of the database for the system.

**Comment by lewisjae1** [comment]
![WorkoutDatabase](https://user-images.githubusercontent.com/86268068/152504807-bea276e5-26b9-42de-855a-3cc2cc167c21.PNG)

## This is the database I got for our workoutbuilder. If you confirm and see nothing wrong I will create another issue about the database and start working on the database!

**Comment by MejiaJ84** [comment]
[](https://cdn.discordapp.com/attachments/936024338283499591/939593577548353546/unknown.png)
[](https://cdn.discordapp.com/attachments/936024338283499591/939593675489554453/unknown.png)
[](https://cdn.discordapp.com/attachments/936024338283499591/939594750690983966/unknown.png)
I'm having trouble envisioning how to make this database and app work practically
I think you and I need to talk with Joe about the functionality of the app and see what is feasible
oddtobias — Today at 10:49 AM
I was thinking maybe something like this:
Image
and then using this form:
Image
select individual muscle groups set the sets and reps and day. (I forgot to add day, but this is just a mock up)
and if they wanted to save a workout to the database, the click save buttton and that would get saved to the workout table
(This is where the optional enhancement comes in) If its just a one-off workout they can export it to an external document
the Add Exercise button works like this:
Image
each time the button is clicked it adds a new row.

**Comment by MejiaJ84** [comment]
Then using this form:
![](https://cdn.discordapp.com/attachments/936024338283499591/939593675489554453/unknown.png)
select individual muscle groups set the sets and reps and day. (I forgot to add day, but this is just a mock up)
and if they wanted to save a workout to the database, they click save buttton and that would get saved to the workout table
(This is where the optional enhancement comes in) If its just a one-off workout they can export it to an external document

**Comment by MejiaJ84** [comment]
The Add Exercise button works like this:
![](https://cdn.discordapp.com/attachments/936024338283499591/939594750690983966/unknown.png)
each time the button is clicked it adds a new row.

**Comment by lewisjae1** [comment]
![unknown](https://user-images.githubusercontent.com/86268068/153291467-62536bd7-a13e-4887-8c4b-9a6688ef3bde.png)

**Comment by lewisjae1** [comment]
I will get rid of Name property in WorkoutOfDay because we can get the name out of workout table using workoutID
